setwd("C:/Users/C16Sara.Menke/Documents/Math378/ExploratoryData/Project1/ExData_Plotting1/exdata-data-household_power_consumption")
data=read.table("./household_power_consumption.txt",header=T,sep=";")
data$Date=as.character(data$Date)
u=(data$Date=="1/2/2007")|(data$Date=="2/2/2007")
subset=data[u,]
remove(data,u)
total.time = paste(subset$Date,subset$Time)
subset$Time=strptime(total.time,format="%d/%m/%Y %H:%M:%S")
subset$Global_active_power=as.character(subset$Global_active_power)
subset$Global_active_power=as.numeric(subset$Global_active_power)
subset$Sub_metering_1=as.character(subset$Sub_metering_1)
subset$Sub_metering_1=as.numeric(subset$Sub_metering_1)
subset$Sub_metering_2=as.character(subset$Sub_metering_2)
subset$Sub_metering_2=as.numeric(subset$Sub_metering_2)
subset$Sub_metering_3=as.character(subset$Sub_metering_3)
subset$Sub_metering_3=as.numeric(subset$Sub_metering_3)
subset$Voltage=as.character(subset$Voltage)
subset$Voltage=as.numeric(subset$Voltage)
subset$Global_reactive_power=as.character(subset$Global_reactive_power)
subset$Global_reactive_power=as.numeric(subset$Global_reactive_power)
png(filename = "plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
par(mar=c(4,4,4,4))
with(subset, {
    plot(Time,Global_active_power,type="l",xlab="",ylab="Global Active Power",main="")
    plot(Time,Voltage,type="l",xlab="datetime",ylab="Voltage",main="")
    plot(Time,Sub_metering_1,type="l",xlab="",ylab="Energy Sub Meeting",main="",col="black")
    lines(Time,Sub_metering_2,type="l",col="red")
    lines(Time,Sub_metering_3,type="l",col="blue")
    legend("topright",lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),bty="n",cex=0.9)
    plot(Time,Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power",main="")
})
dev.off()
